name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.7', '3.0', '3.1' ]

    name: Ruby ${{ matrix.ruby }}

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-use-ruby-${{ runner.os }}-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-use-ruby-${{ runner.os }}-${{ matrix.ruby }}-

      - name: Install bundler
        run: gem install bundler

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run specs
        run: bundle exec rake spec
